app = "video001"
primary_region = "iad"

[build]
  image = "node:20-bullseye"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true

[deploy]
  release_command = "node server.js"
